/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_GUI_Perdida;
import Modelo.MetodosPuntaje;

/**
 *
 * @author Erika
 */
public class GUI_Perdida extends javax.swing.JFrame {

     Controlador_GUI_Perdida controlador_GUI_Perdida;
     MetodosPuntaje metodosPuntaje;
    
    //Metodo constructor de la clase
     public GUI_Perdida() {
        initComponents();
        this.setLocation(500,100);
        
        controlador_GUI_Perdida = new Controlador_GUI_Perdida(this);
        metodosPuntaje= new MetodosPuntaje();
        agregarEventos();
        this.jt_Puntaje.setEditable(false);
        escribir();
    }//Fin del metodo constructor
    
    //Metodo que agrega eventos 
     public void agregarEventos()
    {
        this.btn_OtraVez.addActionListener(controlador_GUI_Perdida);
        this.btn_Salir.addActionListener(controlador_GUI_Perdida);
        this.jt_Nombre.addActionListener(controlador_GUI_Perdida);
        this.jt_Puntaje.addActionListener(controlador_GUI_Perdida);
        this.btn_Guardar.addActionListener(controlador_GUI_Perdida);
    }//Fin del metodo agregarEventos
    
    
     //Metodo que busca y escribe el puntaje alto
     public void escribir() 
     {
        metodosPuntaje.buscar();
        this.setJt_Nombre(metodosPuntaje.getNombre());
        this.setJt_Puntaje(metodosPuntaje.getPuntaje());
    }//Fin del metodo escribir
    
     //Metodo para limpiar la interfaz despues de guardar
     public void limpiar()
     {
        this.jt_Nombre.setText(" ");
        this.jt_Puntaje.setText("0");
     }//Fin del metodo limpiar
     
     //Metodo que devuelve los puntos en el arreglo
     public String[] devolverPuntosEnArreglo() 
    {
        return controlador_GUI_Perdida.devolverPuntosEnArreglo();
    }//Fin del metodo devolverPuntosEnArreglo
     
    //Metodo que obtiene el Nombre
    public String getJt_Nombre() 
    {
        return jt_Nombre.getText();
    }//Fin del metodo getJt_Nombre

   //Metodo que coloca el nombre
    public void setJt_Nombre(String jt_Nombre) 
    {
        this.jt_Nombre.setText(jt_Nombre);
    }//Fin del metodo

    //Meotod que obtiene el puntaje
    public String getJt_Puntaje() 
    {
        return jt_Puntaje.getText();
    }//Fin del metodo

    //Metodo que coloca el puntaje
    public void setJt_Puntaje(int jt_Puntos) 
    {
        this.jt_Puntaje.setText(""+jt_Puntos);
    }//Fin del metodo
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jt_Nombre = new javax.swing.JTextField();
        jt_Puntaje = new javax.swing.JTextField();
        btn_OtraVez = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        btn_Guardar = new javax.swing.JButton();
        jl_FondoPerdida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(845, 760));
        getContentPane().setLayout(null);
        getContentPane().add(jt_Nombre);
        jt_Nombre.setBounds(320, 330, 370, 22);
        getContentPane().add(jt_Puntaje);
        jt_Puntaje.setBounds(320, 390, 370, 22);

        btn_OtraVez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/otra vez.png"))); // NOI18N
        btn_OtraVez.setActionCommand("OtraVez");
        getContentPane().add(btn_OtraVez);
        btn_OtraVez.setBounds(130, 460, 280, 60);

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btn_Salir.setActionCommand("Salir");
        btn_Salir.setContentAreaFilled(false);
        getContentPane().add(btn_Salir);
        btn_Salir.setBounds(740, 640, 91, 60);

        btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoGUARDAR-01.png"))); // NOI18N
        btn_Guardar.setActionCommand("Guardar");
        btn_Guardar.setContentAreaFilled(false);
        getContentPane().add(btn_Guardar);
        btn_Guardar.setBounds(460, 450, 290, 70);

        jl_FondoPerdida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perdiste.png"))); // NOI18N
        getContentPane().add(jl_FondoPerdida);
        jl_FondoPerdida.setBounds(0, 0, 831, 722);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_OtraVez;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jl_FondoPerdida;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_Puntaje;
    // End of variables declaration//GEN-END:variables
}
