/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_GUI_Inicio;
import javax.swing.JOptionPane;

/**
 *
 * @author Erika
 */
public class GUI_Inicio extends javax.swing.JFrame {

   Controlador_GUI_Inicio controlador_GUI_Inicio;
    
   //Metodo constructor de la clse 
   public GUI_Inicio() {
        initComponents();
        this.setLocation(500,100);
        
        controlador_GUI_Inicio= new Controlador_GUI_Inicio(this);
        agregarEventos();
    }//Fin del metodo constructor
    
   //Metodo para agregar eventos a los botones 
   public void agregarEventos()
    {
      this.btn_Jugar.addActionListener(controlador_GUI_Inicio);
    }//Fin del metodo agregar eventos
    
    
    /*
    public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null,mensaje);
    }
    */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Jugar = new javax.swing.JButton();
        jl_FondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(845, 760));
        getContentPane().setLayout(null);

        btn_Jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugar.png"))); // NOI18N
        btn_Jugar.setActionCommand("Jugar");
        getContentPane().add(btn_Jugar);
        btn_Jugar.setBounds(280, 440, 260, 60);

        jl_FondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-02.png"))); // NOI18N
        getContentPane().add(jl_FondoInicio);
        jl_FondoInicio.setBounds(0, 0, 829, 722);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Jugar;
    private javax.swing.JLabel jl_FondoInicio;
    // End of variables declaration//GEN-END:variables
}
